[options]
Architecture = auto
[core] Include = /etc/pacman.d/mirrorlist
[extra] Include = /etc/pacman.d/mirrorlist
[community] Include = /etc/pacman.d/mirrorlist
[outlaw]
SigLevel = Optional TrustAll
Server = https://raw.githubusercontent.com/YOURUSERNAME/outlaw-os/main/outlaw-repo/$arch